package com.belog.models;

import java.io.Serializable;
import java.util.Date;

public class TbPost implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_post.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_post.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_post.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_post.price_times
     *
     * @mbggenerated
     */
    private Integer priceTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_post.look_times
     *
     * @mbggenerated
     */
    private Integer lookTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_post.auth_range
     *
     * @mbggenerated
     */
    private Integer authRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_post.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_post.deleted
     *
     * @mbggenerated
     */
    private Boolean deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_post.topic_id
     *
     * @mbggenerated
     */
    private Long topicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_post.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_post
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_post.id
     *
     * @return the value of tb_post.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_post.id
     *
     * @param id the value for tb_post.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_post.user_id
     *
     * @return the value of tb_post.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_post.user_id
     *
     * @param userId the value for tb_post.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_post.title
     *
     * @return the value of tb_post.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_post.title
     *
     * @param title the value for tb_post.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_post.price_times
     *
     * @return the value of tb_post.price_times
     *
     * @mbggenerated
     */
    public Integer getPriceTimes() {
        return priceTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_post.price_times
     *
     * @param priceTimes the value for tb_post.price_times
     *
     * @mbggenerated
     */
    public void setPriceTimes(Integer priceTimes) {
        this.priceTimes = priceTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_post.look_times
     *
     * @return the value of tb_post.look_times
     *
     * @mbggenerated
     */
    public Integer getLookTimes() {
        return lookTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_post.look_times
     *
     * @param lookTimes the value for tb_post.look_times
     *
     * @mbggenerated
     */
    public void setLookTimes(Integer lookTimes) {
        this.lookTimes = lookTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_post.auth_range
     *
     * @return the value of tb_post.auth_range
     *
     * @mbggenerated
     */
    public Integer getAuthRange() {
        return authRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_post.auth_range
     *
     * @param authRange the value for tb_post.auth_range
     *
     * @mbggenerated
     */
    public void setAuthRange(Integer authRange) {
        this.authRange = authRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_post.create_time
     *
     * @return the value of tb_post.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_post.create_time
     *
     * @param createTime the value for tb_post.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_post.deleted
     *
     * @return the value of tb_post.deleted
     *
     * @mbggenerated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_post.deleted
     *
     * @param deleted the value for tb_post.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_post.topic_id
     *
     * @return the value of tb_post.topic_id
     *
     * @mbggenerated
     */
    public Long getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_post.topic_id
     *
     * @param topicId the value for tb_post.topic_id
     *
     * @mbggenerated
     */
    public void setTopicId(Long topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_post.content
     *
     * @return the value of tb_post.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_post.content
     *
     * @param content the value for tb_post.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_post
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", title=").append(title);
        sb.append(", priceTimes=").append(priceTimes);
        sb.append(", lookTimes=").append(lookTimes);
        sb.append(", authRange=").append(authRange);
        sb.append(", createTime=").append(createTime);
        sb.append(", deleted=").append(deleted);
        sb.append(", topicId=").append(topicId);
        sb.append(", content=").append(content);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}